name: Automatically restart docker container

on:
 
  workflow_dispatch:
    inputs:
      # keynm:
      #   description: 'Enter the key name'
      #   required: true
      #   default: ''
      user_name:
        description: 'Enter the user name'
        required: true
        default: ''
      ip_address:
        description: 'Enter the ip address'
        required: true
        default: ''
      container_name:
        description: 'Enter the conatiner name that you want to restart'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restart the container
      run: |
        sudo chmod +x restartdoc.sh
        sudo sh restartdoc.sh -u ${{ github.event.inputs.user_name }} -p {{ github.event.inputs.ip_address }} -c {{ github.event.inputs.container_name }}
   
