name: Automatically restart docker container

on:
  repository_dispatch:
    types: qbot_restart

  workflow_dispatch:
    inputs:
      # keynm:
      #   description: 'Enter the key name'
      #   required: true
      #   default: ''
      user_name:
        description: 'Enter the user name. (ec2-user, ubuntu)'
        required: true
        default: 'ec2-user'
      ip_address:
        description: 'Enter the ip address'
        required: true
        default: '172.31.96.27'
      container_name:
        #type: choice
        description: 'Enter the conatiner name that you want to restart. (Nginx, Apache)'
        # options:
        # - Nginx
        # - Apache
        required: true
        default: 'Nginx'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Restart the container
      run: |
        pwd
        sudo chmod +x ./restartdoc.sh
        sudo ./restartdoc.sh -u ${{ github.event.inputs.user_name }} -p ${{ github.event.inputs.ip_address }} -c ${{ github.event.inputs.container_name }} -s ${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}
        echo $sucess
        
    - name: Slack Notification
      if: success()
      run: |
        SLACK_WEBHOOK_URL=${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}
        notify_string="Docker Container Restart Successful \n Please monitor after 10-15 min and check where the Qbot alarm solve or not \n https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:?~(alarmStateFilter~'ALARM) \n It is also in ALarm state then Check the Qbot Server"
        curl -sk -d "payload={\"channel\": \"#alerts-low-priority\", \"username\": \"Docker Container Restart Successful\", \"text\":  \"${notify_string}\"}" ${SLACK_WEBHOOK_URL}

    - name: Failure Notification
      if: failure()
      run: |
        SLACK_WEBHOOK_URL=${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}
        notify_string="Docker Container Restart 'Fails'" 
        curl -sk -d "payload={\"channel\": \"#alerts-low-priority\", \"username\": \"Docker Container Restart Fails\", \"text\":  \"${notify_string}\"}" ${SLACK_WEBHOOK_URL}


    # - name: Success Notification
    #   if: Success()
    #   run: |
    #     ./github_slack.sh '${{ github.event_name }}' 'Success' '@here Docker Container Restart Success' '${{ env.ACTION_URL }}' '${{ github.event.repository.html_url }}' 'Docker Containers Restart Successful' '${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}' '' '${{ github.actor }}'
