name: Automatically restart docker container

on:
 
  workflow_dispatch:
    inputs:
      key:
        description: 'Enter the key name'
        required: true
        default: ''
      user_name:
        description: 'Enter the user name'
        required: true
        default: ''
      ip_address:
        description: 'Enter the ip address'
        required: true
        default: ''
      container_name:
        description: 'Enter the conatiner name that you want to restart'
        required: true
        default: ''

jobs:

  build:

    runs-on: linux-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restart that container
      run: |
        chmod +x restartdoc.sh
        sh dokstart.sh -k nginx1.pem -u ec2-user -p 10.0.2.181 -c Nginx
   
      env:
        name: build
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
