name: Automatically restart docker container

on:

  workflow_dispatch:
    inputs:
      # keynm:
      #   description: 'Enter the key name'
      #   required: true
      #   default: ''
      user_name:
        description: 'Enter the user name'

        required: true
        default: 'ec2-user'
      ip_address:
        description: 'Enter the ip address'
        required: true
        default: '172.31.96.27'
      container_name:
        type: choice
        description: 'Enter the conatiner name that you want to restart'
        options:
        - Nginx
        - Apache
        required: true
        default: 'Nginx'

jobs:
  build:
    runs-on: self-hosted
    env:
      ACTION_URL: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}

    steps:
    - uses: actions/checkout@v2
    - name: Restart the container
      run: |
        sudo chmod +x ./restartdoc.sh
        sudo ./restartdoc.sh -u ${{ github.event.inputs.user_name }} -p ${{ github.event.inputs.ip_address }} -c ${{ github.event.inputs.container_name }} -s ${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}
        echo $sucess
        
    - name: Slack Notification
      if: sucess()
      run: |
        SLACK_WEBHOOK_URL= $slackvar
        notify_string="Test String" 
        curl -sk -d "payload={\"channel\": \"#low-high-priority\", \"username\": \"Docker Container Restart Successful\", \"text\":  \"${notify_string}\"}" ${SLACK_WEBHOOK_URL}


    # - name: Success Notification
    #   if: Success()
    #   run: |
    #     ./github_slack.sh '${{ github.event_name }}' 'Success' '@here Docker Container Restart Success' '${{ env.ACTION_URL }}' '${{ github.event.repository.html_url }}' 'Docker Containers Restart Successful' '${{ secrets.SLACK_GITHUB_ACTIONS_ALERTS_WEBHOOK }}' '' '${{ github.actor }}'
