name: Automatically restart docker container

on:

  workflow_dispatch:
    inputs:
      # keynm:
      #   description: 'Enter the key name'
      #   required: true
      #   default: ''
      user_name:
        description: 'Enter the user name'

        required: true
        default: 'ec2-user'
      ip_address:
        description: 'Enter the ip address'
        required: true
        default: '172.31.96.27'
      container_name:
        #type: choice
        description: 'Enter the conatiner name that you want to restart'
        options:
        - Nginx
        - Apache
        required: true
        default: 'Nginx'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Restart the container
      run: |
        ls
        sudo chmod +x ./restartdoc.sh
        sudo sh ./restartdoc.sh -u ${{ github.event.inputs.user_name }} -p ${{ github.event.inputs.ip_address }} -c ${{ github.event.inputs.container_name }}
